# Generated by Django 3.0.2 on 2020-05-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
