# Generated by Django 3.0.2 on 2020-06-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
